# Generated by Django 4.2.5 on 2025-10-29 22:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_cpd_funcionarios_cpf'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
